### ISSUE TITLE
SDK isn't in Maven

### ISSUE THREAD

**Issue by checketts** [domoinc/domo-java-sdk#1]
The SDK is open source and will be in Maven shortly.

Follow this issue to be notified when that work has been completed.

**Comment by zawataki** [comment]
When will SDK be in Maven?

**Comment by rswingler** [comment]
@checketts

**Comment by checketts** [comment]
@tkzwyk I hope to get it to bintray in the next week or 2. Maven central will likely follow shortly afterwards.

**Comment by zawataki** [comment]
@checketts I got it. I look forward to the release. 😄
Thank you for response.

**Comment by checketts** [comment]
This has now been uploaded to Bintray/Jcenter

Via maven
```xml
<dependency>
  <groupId>com.domo</groupId>
  <artifactId>domo-java-sdk-all</artifactId>
  <version>0.1.0</version>
</dependency>
```

Gradle
```
compile 'com.domo:domo-java-sdk-all:0.1.0'
```

Maven repository:
```
repositories {
    maven {
        url  "http://dl.bintray.com/domoinc/domo-java-sdk" 
    }
}
```

See the `Set Me Up` button on https://bintray.com/domoinc/domo-java-sdk/domo-java-sdk for more details.

I'm leaving this issue open until our release process publishes all the way to maven central.

**Comment by vikas-tikoo-zefr** [comment]
Had to remove ```<type>pom</type>``` to make it work.

**Comment by checketts** [comment]
> Had to remove <type>pom</type> to make it work.

Oops. Updated my comment. Sorry I had tested it with gradle. Thanks for the feedback.

**Comment by zoosm3** [comment]
https://github.com/domoinc/domo-java-sdk
Setup tells to use version 0.3.0, but it is not available in Maven. I could use 0.20. instead like this: 
```
<dependency>
  <groupId>com.domo</groupId>
  <artifactId>domo-java-sdk-all</artifactId>
  <version>0.2.0</version>
</dependency>
```
Can you please upload 0.3.0 to Maven as well?

**Comment by checketts** [comment]
Thanks for the report. We changed our publishing automation. 

I'll look into it. It appears to be uploaded here: https://bintray.com/domoinc/domo-java-sdk/domo-java-sdk/0.3.0

**Comment by zawataki** [comment]
Thank you for all support!
