### ISSUE TITLE
Full authentication is required to access this resource

### ISSUE THREAD

**Issue by gdhanraj** [domoinc/domo-java-sdk#14]
I am trying to use the Java SDK to access a stream, when I run the app I get the following error

Exception in thread "main" com.domo.sdk.request.RequestException: Error making request url:https://api.domo.com/v1/streams/662?fields=all reponseBody:{"status":401,"statusReason":"Internal Server Error","path":"/v1/streams/662","message":"com.domo.bedrock.service.exception.UnauthorizedException: Full authentication is required to access this resource","toe":"O6Q67O9N7H-U3ALR-NVA7L"}

**Comment by rswingler** [comment]
Are you seeing this error with any other part of the SDK? (users, groups, datasets, etc?) Or is this issue only with the Streams client?

This may be as simple as creating a new Client ID/Secret: https://developer.domo.com/docs/authentication/overview-4

**Comment by gdhanraj** [comment]
Hi, 

Thanks for your reply.

I did create a new client ID/Secret in the sandbox environment,  I ran the create example for datasets, streams and groups and got the same error.

I also tried a small test app with existing credentials that I use to connect to the API via MuleESB, same result.

**Comment by rswingler** [comment]
Do you mean a Developer Sandbox environment, like "https://myname-dev-1000.demo.domo.com" ? It appears creating API Clients for Developer Sandboxes is currently broken on developer.domo.com. I can't create an API client for my own sandbox instance :(

Or is your environment a normal one, ie "https://mycompany.domo.com"?

I'm running some tests using the SDK.

**Comment by gdhanraj** [comment]
Yes I did use the Developer Sandbox, I guess that's a dud then!

The other clientID/Secret is for a live instance that belongs to a client, I know it works because I have data streams updated daily via the API.

This is my simple test

       Config config = Config.with()
                        .clientId("XXX")
                        .clientSecret("YYY")
                        .apiHost("api.domo.com")
                        .useHttps(true)    
                        .scope(Scope.USER, Scope.DATA)              
                        .httpLoggingLevel(HttpLoggingInterceptor.Level.BODY)
                        .build();
           
		DomoClient domo = DomoClient.create(config);
    
        //Manage Streams
        StreamClient streams = domo.streamClient();
        System.out.println("Listed Streams: " + streams.list(110, 0));

**Comment by rswingler** [comment]
Sorry about the trouble - I'm opening a ticket to get this resolved.

**Comment by gdhanraj** [comment]
Thank you

**Comment by ramamohank** [comment]
Hi 
Is there any update on this ?  
Ram

**Comment by rswingler** [comment]
Hi Ram,

I apologize this fell through the cracks. My original work involved discussions with the engineers that oversee the developer sandboxes. I'm looking into this again.

**Comment by rswingler** [comment]
There was a discrepancy between the developer sandboxes given to Domo engineers vs the sandboxes given to the public. 

To confirm, does the following work?
- Go to https://developer.domo.com/login
- Log in using your sandbox domain, eg 'myname-dev-etc.domo.com'
- On the "My Account" dropdown, click "New Client"
- Enter a name for the client and select any scopes you wish
- Click create

Were you able to create a new client for your sandbox? You mentioned you had one already, but I wanted to confirm that creating clients works.

**Comment by rswingler** [comment]
I was able to create a sandbox, create a client, and run tests using the Java SDK, where all of the stream-related tests passed. However, the sandbox I was given is on a different domain than yours. 

What is the URL for your sandbox?

**Comment by gdhanraj** [comment]
I created a new client at https://govind-dev-118049.domo.com/page/293805565 and it worked, I was able to list a stream.

It still doesn't work for the live client, would creating a new client solve that problem?

**Comment by rswingler** [comment]
Creating a new client may solve the issue. When making requests from the SDK, make sure that the scopes in the SDK match the scopes you configured on developer.domo.com when creating the client.

And I thought you said the live client works - you mentioned "The other clientID/Secret is for a live instance that belongs to a client, I know it works because I have data streams updated daily via the API."

Did something break in the mean time?

**Comment by gdhanraj** [comment]
The live client ID works from Mule ESB using the API, it fails when using the SDK with the full authentication error.

**Comment by rswingler** [comment]
The SDK may fail if the scopes are mis-matched. Also, ensure the Mule ESB and the SDK are pointing at the same API host (I believe they should both be api.domo.com). Also check the "https" configuration for both the ESB and the SDK (they should both be "https" when making calls). Also try creating a new client. Let me know if it still doesn't work after attempting these checks.

**Comment by gdhanraj** [comment]
The url is the same and both are set to use HTTPS, I asked the client to create a new set of creds, once I get that, I'll confirm if it works.

**Comment by gdhanraj** [comment]
I got it work using the 'DATA' scope, for Mule and Postman I use 'client_credentials', which I presumed was 'USER' scope.
