### ISSUE TITLE
"bootRepackage" Not Found

### ISSUE THREAD

**Issue by KSilverman** [domoinc/domo-java-sdk#2]
I am trying to get the external jars to add to my Domo project. I cloned the respository, but I get this error when I run the command "./gradlew bootRepackage".

![err](https://cloud.githubusercontent.com/assets/5942751/26423920/742751d8-409d-11e7-8e13-9ec26a3a5ab6.PNG)

Any reason as to what could be the cause of this? Thanks!

**Comment by checketts** [comment]
`bootRepackage` is a SpringBoot specific task used to create a fat/executable jar. If you are trying to publish to your local maven repo you would use `./gradlew publishToMavenLocal` (or shortened to `./gradlew pTML`)

I'll update the readme. Sorry about that.

**Comment by rswingler** [comment]
My mistake; "bootRepackage" is a Spring feature. I'll get this updated.

**Comment by rswingler** [comment]
@KSilverman I've updated the readme:

Classic Jar Import:
- Clone this repository
- Using a Bash Terminal, navigate to the cloned repository folder
- Create the Jar files via the Bash command `./gradlew publishToMavenLocal`
- The Jars will be located in `domo-java-sdk-all/build/libs/`
- Copy the Jars to your project folder, and add them to your build path

**Comment by checketts** [comment]
Instead of copying the jars, referencing the local maven repo is better along with installing the jar into whatever maven repo you might use (if you have an internal one). 

I'll try to fast track publishing the artifacts. See #1
