### ISSUE TITLE
version 0.4.2 and 0.4.3 don't contain Java classes

### ISSUE THREAD

**Issue by zawataki** [domoinc/domo-java-sdk#20]
I have tried using version 0.4.2 and 0.4.3. But they don't contain Java classes as below:
![Screen Shot 2021-03-09 at 9 58 38](https://user-images.githubusercontent.com/17080085/110402558-f35c8300-80be-11eb-9eb2-687d8786e9a5.png)

Version 0.4.1 contains Java classes but I would like to use [DataSetClient#query method](https://github.com/domoinc/domo-java-sdk/blob/3afa9a1ae14318a554fbde9d3a2f476e948264d6/domo-java-sdk-all/src/main/java/com/domo/sdk/datasets/DataSetClient.java#L154) that not contained in version 0.4.1.

**Comment by ryanmurf** [comment]
@zawataki I uploaded artifact 'domo-java-sdk-all'. Let me know if you have any issues.
```
<dependency>
  <groupId>com.domo</groupId>
  <artifactId>domo-java-sdk-all</artifactId>
  <version>0.4.3</version>
</dependency>
```

**Comment by zawataki** [comment]
@ryanmurf Thank you for your uploading. Let me check it.

**Comment by zawataki** [comment]
@ryanmurf It works. Thank you.
