### ISSUE TITLE
Developers need 'sandbox' api access

### ISSUE THREAD

**Issue by zawataki** [domoinc/domo-java-sdk#6]
I am now using the SDK in work, but would like to use in private as well.
But I have no Domo account, so I cannot access Domo API.
I tried to sign up free account a few days ago, but response is nothing...

Should I do what to join developement the SDK and get client Id and client secret?

**Comment by checketts** [comment]
This is in the works. I'll update this ticket when it is released.

**Comment by checketts** [comment]
Sandbox access is now available: https://developer.domo.com/dev-sandbox-request

**Comment by zawataki** [comment]
Thank you very much!!
I will try it.
