### ISSUE TITLE
Client Test File link under Usage section is broken

### ISSUE THREAD

**Issue by aaronsperry** [domoinc/domo-java-sdk#9]
The link to the Client Test File is broken:

https://github.com/domoinc/domo-java-sdk/blob/master/domo-java-sdk-all/src/test/java/com/domo/sdk/ClientTest.java

Please fix.

**Comment by rswingler** [comment]
Sorry about that; the file was removed by mistake. It's been restored: https://github.com/domoinc/domo-java-sdk/blob/master/domo-java-sdk-all/src/test/java/com/domo/sdk/ClientTest.java

**Comment by ghost** [comment]
Hi! This `ClientTest` file, mentioned in the readme, appears to be lost again. I searched the repo for "ClientTest", but didn't come up with anything.
